# Generated by Django 4.1.3 on 2022-11-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_directorytype_directories_dir_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directories',
            name='dir_name',
            field=models.CharField(max_length=4096, unique=True),
        ),
    ]
